name: ethller_api_interface
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  pedantic: ^1.9.0
dependencies:
  flutter:
    sdk: flutter
  flutter_test_ui: ^1.0.0
  http: ^0.12.2
  mockito: ^4.1.4
  test: ^1.15.7
